### ISSUE TITLE
Use bitcoincash: as URI when sharing a BCC address

### ISSUE THREAD

**Issue by torusJKL** [Bitcoin-com/Wallet#11]
When using the share function on the Android wallet the used URI is bitcoin:<address> no matter if the address is from a BTC or BCC wallet.

On the [bitcoin-ml mailing list](https://lists.linuxfoundation.org/pipermail/bitcoin-ml/2017-August/000102.html) the majority has agreed to use bitcoincash: instead to have a distinctive URI for Bitcoin Cash.

It would help if the Bitcoin.com wallet would adopt this URI as well for Bitcoin Cash address sharing.

**Comment by aminnich** [comment]
Ok. Thank you for Information!

Alex

**Comment by cranau** [comment]
Tried to use the prefix today for the Bitcoin Cash marketing initiative. We had to make a separate QR Code because the Bitcoin.com wallet could not interpret the `bticoincash:` prefix.

https://www.yours.org/content/now-that-the-debate-is-over--lets-finally-make-some-progress-forward---35e74b0abdcc/?utm_content=buffer3d11d&utm_medium=social&utm_source=twitter.com&utm_campaign=buffer

**Comment by alfonsofy** [comment]
Hello everybody, 

This has been fixed. Thank you for reporting.

**Comment by brendoncoin** [comment]
Fixed.
