### ISSUE TITLE
Add CashShuffle support

### ISSUE THREAD

**Issue by abrkn** [Bitcoin-com/Wallet#34]
![](https://api.bountysource.com/badge/issue?issue_id=52741547)

Add optional [CashShuffle](https://cashshuffle.com/) support when sending transactions.

The lack of fungibility/privacy in Bitcoin Cash introduces a number of problems:

- Some centralized exchanges will suspend user accounts if deposits are (indirectly) coming from DarkNet Market places, gambling websites, etc.
- It's trivial to perform clustering to identify the real life identity, transaction history, and balance of a wallet from a single transaction. ([Chainalysis](https://www.chainalysis.com/), [WalletExplorer](https://www.walletexplorer.com/))

To get around these issues, users are fleeing to digital currencies with improved privacy such as Monero, Zcash, Zcoin, Dash, and more.

Bitcoin Cash is **A Peer-to-Peer Electronic Cash System**. Fungibility is an attribute of cash and thus a requirement.

- [CashShuffle Documentation](https://github.com/cashshuffle/cashshuffle-electron-cash-plugin/wiki/Documentation)
- [Reference implementation (Electron Cash plugin)](https://github.com/cashshuffle/cashshuffle-electron-cash-plugin)

If you can't help with coding, please consider [adding $5 to the bounty](https://www.bountysource.com/issues/52741547-add-cashshuffle-support). Everything helps.

**Comment by magmahindenburg** [comment]
We would love to add CashShuffle.
For this to happen we need a JavaScript implemetation that works with the Bitcore libraries.

**Comment by jli225** [comment]
Blockchain info ever implemented such service years ago.
Glad to see that Bitcoin com makes it again.
Although I dislike most DNM,  I firmly believe that Government and its agents have infringed people's privacy too much.

**Comment by stefment** [comment]
@magmahindenburg is CashShuffle safe?

**Comment by PedroR82** [comment]
The Bountysource thingy accepts Paypal and Bitcoin.
Could you enable a Bitcoin Cash address for this?
I would send something in the range of 50$ to that address if so...

**Comment by PedroR82** [comment]
Or even better, get the bountysource team to add Bitcoin Cash there.

**Comment by lvella** [comment]
@PedroR82 There is an open issue about that (and a corresponding bounty):
https://github.com/bountysource/core/issues/1136
https://www.bountysource.com/issues/49027183-add-bitcoin-cash-support-to-bountysource

**Comment by patsul12** [comment]
I'd be happy to do some work on this, or help out someone who is already doing so. I'm assuming this would be a standalone javascript implementation of the CoinShuffle protocol that is then integrated into this wallet?

**Comment by abrkn** [comment]
There is already an open issue to add Bitcoin Cash (BCH) to BountySource: https://github.com/bountysource/core/issues/1136

**Comment by bookmoons** [comment]
Hi guys. Would really love to make this happen. I've been reading through the [CashShuffle](https://cashshuffle.com/) and [CoinShuffle](http://crypsys.mmci.uni-saarland.de/projects/CoinShuffle/) and [ECIES](https://cryptopp.com/wiki/Elliptic_Curve_Integrated_Encryption_Scheme) material.

I have some code toward it here: [cashshufflejs](https://github.com/bookmoons/cashshufflejs). I'm favoring correctness and code clarity over performance for the initial release. [Bug reports](https://github.com/bookmoons/cashshufflejs/issues) and code review welcome. It doesn't talk to the BCH network yet but it's possible to run the tests:

```shell
$ git clone https://github.com/bookmoons/cashshufflejs.git
$ cd cashshufflejs
$ npm install
$ npm test
```

It uses a couple new modules that are just the extant bitcore modules modified to use [bitcore-lib-cash](https://www.npmjs.com/package/bitcore-lib-cash) instead of bitcore-lib.
* [@bookmoons/bitcore-ecies-cash](https://www.npmjs.com/package/@bookmoons/bitcore-ecies-cash)
* [@bookmoons/bitcore-message-cash](https://www.npmjs.com/package/@bookmoons/bitcore-message-cash)

CashShuffle is an extension to CoinShuffle. The core of the CoinShuffle session is implemented. The blame phase is pending. Bits around it are pending, eg joining a pool, retries after ejecting a bad participant.

The session looks like this. There are [diagrams of the phases](https://github.com/bookmoons/cashshufflejs/wiki/Protocol) on the wiki.

![Shuffle Diagram](https://github.com/bookmoons/cashshufflejs/wiki/img/SessionStatechart.png)

There are docs up here: [cashshufflejs docs](https://bookmoons.github.io/cashshufflejs/). The interfaces are defined carefully. The [original CashShuffle docs](https://github.com/cashshuffle/cashshuffle-electron-cash-plugin/wiki/Protocol-Description) are a little haphazard. Hoping to make things more lucid and precise. For example: the [message encryption interface](https://bookmoons.github.io/cashshufflejs/interface/crypto.html).

The docs use some custom extensions to [sphinx-js](https://github.com/erikrose/sphinx-js). Some pieces need polishing (longer than necessary paths are displayed, typedefs are rendered as functions). But I think the important details are visible. I'm working on submitting those changes for inclusion. Would like to get the docs up on [ReadTheDocs](https://readthedocs.org/).
* Support text form of `@see` tag. erikrose/sphinx-js#70
* Allow Markdown in descriptions. erikrose/sphinx-js#69
* A new `autointerface` directive
* A new `automodule` directive

A question for whoever knows: what is the right way to interface with the BCH network? [Copay](https://github.com/bitpay/copay) calls itself a network interface but it doesn't seem to provide things like checking available funds of an address.

**Comment by bookmoons** [comment]
There are things I find disquieting in the reference implementation. I'd like to propose some breaking changes and ask anyone interested for comment. A [shuffling server was actually shut down](https://www.reddit.com/r/btc/comments/8fp8ee/shufflecash_i_started_a_new_public_cashshuffle/) due to concerns about the code. So I think we may have an opportunity to get some changes in before significant usage starts.

**ECIES configuration.** ECIES is a very general scheme with many possible configurations. There doesn't seem to be a JavaScript library that provides the full range. We're targeting bitcore compatbility, so I went with the [bitcore-ecies](https://www.npmjs.com/package/bitcore-ecies) module [modified for Bitcoin Cash](https://www.npmjs.com/package/@bookmoons/bitcore-ecies-cash). I propose we choose the default configuration of this module. I've [specified it that way](https://bookmoons.github.io/cashshufflejs/interface/crypto.html) in the docs:

>Performs ECIES encryption with the bitcore-ecies 1.0.3 default configuration.

**Wire delimiting.** The reference code delimits messages on the wire with the Unicode character [`U+23CE Return Symbol`](https://codepoints.net/U+23CE) in UTF-8. That comes out to the 3 byte sequence `e2 8f 8e`. I don't think there's any guarantee that byte sequence will not appear in messages. I'm really concerned this will cause broken messages. Proposed fix: write the message byte length preceding each message, as [recommended in the protobuf docs](https://developers.google.com/protocol-buffers/docs/techniques#streaming).

**Output list serialization.** The protocol produces a list of output addresses, transferred first encrypted and eventually in plaintext once shuffling is done. The reference code does a strange thing here of packaging into multiple packets and seems not to sign the full list. I'm concerned this is a security hole. The reference code is based on the CoinShuffle implementation [ShufflePuff](https://github.com/DanielKrawisz/Shufflepuff). I think this is an attempt to mimic the ShufflePuff approach of using multiple `Atom` instances that are somehow serialized. Proposed fix: define a serialization and store the full list in the single `packet.message.str` field. I have this specified and implemented as delimited with ampersand `&`. That's a character not in either the Base64 representation used for ciphertexts or the [CashAddr](https://github.com/bitcoincashorg/bitcoincash.org/blob/master/spec/cashaddr.md) format used for addresses. Being in a single packet the entire list will be signed when the packet is signed.

**Hash function input.** Phase 4 runs an equivocation check. At this point the output list is known. Everyone hashes it (along with encryption public keys 2-N) and confirms that all hashes are identical. The reference code serializes these lists with the Python [str()](https://docs.python.org/3/library/stdtypes.html#str) function. This doesn't seem like a safe way to serialize. The docs say it gives _the “informal” or nicely printable string representation of object_. I'm not sure this format is even specified anywhere, or identical across Python versions. I think we need to define a precise format for this input. Proposed format: `[ ...encryptionKeys, ...outputList ].join('')`, where encryption keys are little endian hex strings in order 2-N, output list is CashAddr strings in order observed in the final message that broadcasted it.

**Multiple inputs per user.** The reference code (and ShufflePuff) require exactly 1 UTXO per shuffle participant. I want to suggest we lift this limitation and allow multiple. I'm not sure if there are issues with this that motivated ShufflePuff to avoid it. But it seems like a pain to force users to do a staging transaction before they can shuffle. Related to this, a suggested new repeated field in the protocol `message.signatures` that enables clean transfer of multiple signatures. This is used in phase 5 where the transaction is signed and everyone exchanges their signatures.

**Comment by bookmoons** [comment]
>Copay calls itself a network interface but it doesn't seem to provide things like checking available funds of an address.

Was thinking of the [Bitcore Wallet Service](https://github.com/bitpay/bitcore-wallet-service) here. It's called the network interface but it doesn't seem to provide everything.

>Copay depends on Bitcore Wallet Service (BWS) for blockchain information, networking and Copayer synchronization.

**Comment by christroutner** [comment]
@bookmoons The BITBOX project is also interested in adding CashShuffle support. I've opened an issue to explore, and I welcome you input:
https://github.com/Bitcoin-com/bitbox-javascript-sdk/issues/26

We have an SDK for low-level transactions as well as high-level HD wallets. Here are some example apps using BITBOX:
https://github.com/Bitcoin-com/bitbox-javascript-sdk/tree/master/examples

Introduction to the SDK:
https://developer.bitcoin.com/bitbox

Our API documentation:
https://developer.bitcoin.com/bitbox/docs/getting-started

I welcome you to join our Discord channel so that we can discuss how we could implement a cash shuffle with your library using our SDK: https://discord.gg/m5h28ND

**Comment by bookmoons** [comment]
@chrisroutner Very interesting, thanks for pinging me. I'm dug into another project for a little while here, then I'll be getting back to this. Will look things over when I get my head back into it.

**Comment by autun12** [comment]
is anyone still working on this

**Comment by yuriy-yarosh** [comment]
I do

**Comment by autun12** [comment]
If no one is working on it I would like to.

**Comment by vegus666** [comment]
Ask for baccarat, betting website, online casino website Baccarat Web vegus168 Football betting website ufabet football betting website[ vegus168 ](url)
[url=https://www.vegusbet.net]vegusbet[/url]
[url=https://www.vegusbet.net/category/vegus168/]vegusbet[/url]
[url=https://www.vegusbet.net/สมัครสมาชิก/]vegusbet[/url]
[url=https://www.vegusbet.net/category/ฟุตบอลต่างประเทศ/]vegusbet[/url]
[url=https://www.vegusbet.net/แทงบอลออนไลน์/]vegusbet[/url]
[url=https://www.vegusbet.net/category/article/]vegusbet[/url]

**Comment by abrkn** [comment]
The wallet has been deprecated in favor of another. The bounty is closed.
