### ISSUE TITLE
Private key and 12 word mnemonic left sitting in clear text in logfile on disk

### ISSUE THREAD

**Issue by jidanni** [Bitcoin-com/Wallet#47]
After creating a wallet and exiting the program, one finds
 ```
-rw------- 1 57002 12-25 11:41 ~/.config/bitcoin.com/Default/Local App Settings/pklphnccpcfcpldhflhcabnihgpicbpi/000003.log
```
is left sitting on disk, with the private keys and 12 word mnemonic in clear text. Seen on Linux.

**Comment by jidanni** [comment]
@dabura667 @matiu  could you check if https://github.com/bitpay/copay/ is also affected?

**Comment by dabura667** [comment]
I vaguely remember an issue about it a while back... can't remember if they removed it or if they explained it away with some sort of "meh, if someone gets access to your physical device you're screwed either way" or something like that.

I'll install and check real quick. brb

**Comment by dabura667** [comment]
ok, I have verified that https://github.com/bitpay/copay/commit/a615abcc2a259fb699485d3d1dbe3b27ed87d4aa has the same problem.

**Comment by dabura667** [comment]
Found with the following command.
```bash
# add a space before grep to prevent it from entering .bash_history
dabura667@linux ~ $  grep -r "session enjoy click flag elevator fortune public hat equal you above junk" ~/.config/copay/
Binary file /home/dabura667/.config/copay/Default/Local App Settings/fmfiokedacobbphpmdlmbjddcbnmgbko/000003.log matches
```

**Comment by jidanni** [comment]
OK I hope you can get through to all downstream affected projects. I haven't had much luck via this bug tracker.

**Comment by jidanni** [comment]
Not only do they need to stop writing them in that file, they need to clean up existing files...

**Comment by dabura667** [comment]
```
xPrivKey
requestPrivKey
walletPrivKey
personalEncryptingKey
sharedEncryptingKey
mnemonic
entropySource
```

These are the attributes of the object being logged that should be removed if present.

They are not present if you set an encryption password ("spending password") as the whole object is encrypted using sjcl.

**Comment by dabura667** [comment]
https://github.com/bitpay/copay/blob/9e3d1b9e8fabcc2c589387102e542568868a25e3/src/js/services/historicLog.js#L36

ahhh it looks like they fixed with an old version... then they added mnemonics and changed the key name of the object and forgot to update this one line.

This should be an easy pull request.

**Comment by dabura667** [comment]
`msg = msg.replace('/xpriv.*/', 'xpriv[Hidden]');`

Wait a sec... this doesn't even make sense... it's trying to do regex but failing horribly.

hmm.

**Comment by jidanni** [comment]
Well, such fixes will only fail the next time in the same way when something gets changed.

**Comment by allthatmoney** [comment]
don't anyone ever post those 12 words here in the forum just in case you been getting ideas.

**Comment by Rterrazas** [comment]
I need a donation to start

**Comment by matiu** [comment]
@dabura667 please see https://github.com/bitpay/copay/issues/7795#issuecomment-359437268 . Thanks.

**Comment by Bitcoin-Ornn** [comment]
Hey jidanni,

I have gone ahead and reported this to the development team, if I need further information I'll be sure to follow-up.

As always thanks for the report and hopefully we can address this issue soon.

Regards,
Ornn.

**Comment by panteo** [comment]
Any news about this serious security issue?

**Comment by allthatmoney** [comment]
i suggest if you have been using bitpay or copay that you take all your money out and move it to a private exodus wallet before it's too late. i was using copay and i copied a btc address from my wallet to send to and it never made it. when i wrote support i was told the btc address i used was not a copay btc address. so if i can copy and paste an address from my private account that is not a copay btc address then they have to be seriously compromised. i also have a friend that lost money from his copay debit card he was using for over a year. i switched to an exodus wallet as my private desktop wallet and opened a coinbase wallet as my backup  so i could get a debit card, which is better anyway because they convert the exact amount of btc from your coinbase wallet for the exact amount you spend and no money is ever stored on your debit card. i have never had any problems since. coinbase also gives both you and your sponsor a gift when you dep your first 100.00 or more into your account. http://www.coinbase.com/join/midwestcore
